[package]
name = "microservice"
version = "0.1.0"
authors = ["goldsborough <peter@goldsborough.me>"]

[dependencies]
diesel = {version="1.1.0", features = ["mysql"]}
env_logger = "0.5.3"
futures = "0.1.17"
hyper = "0.11.14"
log = "0.4.1"
maud = "0.17.2"
mysql = "*"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
syn = "0.12.7"
url = "1.6.0"
